#!/bin/bash
##
#
# Quelle: Komillitonme (Rene Galow)
##
FOLDER=$1
CONFIGFILE=$2
CSVFOLDER=$(dirname $0)
MESSSTELLENNAME=`basename $FOLDER` 
IMPORTFOLDER=$CSVFOLDER"/import/"$MESSSTELLENNAME
STRING=""
OIFS=$IFS
NOWFILE=$(date +"%Y-%m-%d".csv)
#IFS=' '

if [ -d $FOLDER ] ;then
  if [ ! -d $IMPORTFOLDER ] ;then
    	echo "Create Importfolder: "$IMPORTFOLDER
		mkdir -p $IMPORTFOLDER
  fi
  FILES=$(ls "$FOLDER" | grep .csv)
  #echo "FILES: "$FILES
  set $FILES
  while [ $# -gt 0 ]       #Solange die Anzahl der Parameter ($#) 
  do                   
    if [ ! -e $IMPORTFOLDER/$1 ];then
      #echo $CSVFOLDER"/importfromcsv "$FOLDER"/"$1" "$CONFIGFILE
      if [ $1 != $NOWFILE ]; then
	      $CSVFOLDER/importfromcsv $FOLDER/$1 $CONFIGFILE
   	   cp $FOLDER/$1 $IMPORTFOLDER
      	echo "FILE: "$1" imported" 
		fi
    fi
    shift  #Parameter verschieben $2->$1, $3->$2, $4->$3,...
  done
fi
 
IFS=$OIFS

