bachelorarbeit: src/main.cpp src/buswareS0.cpp src/buswareS0.h src/DataStruct.h src/Konfiguration.h src/Konfiguration.cpp src/Deamon.cpp src/Deamon.h src/WriteCSV.cpp src/WriteCSV.h
	 gcc -o bachelorarbeit  src/main.cpp src/buswareS0.cpp src/Deamon.cpp src/Konfiguration.cpp src/WriteCSV.cpp -lconfig++ -lpthread -lstdc++
